variables:
  PLUGIN: 'filter_couponinput'
  PATHNAME: 'filter/couponinput'
  REPOURL: 'https://github.com/sebsoftnl/moodle-filter_couponinput'

include:
  - project: 'sebsoft/open-source/gitlab'
    file: '/opensource-plugin/opensource-plugin-405+.yml'
    ref: main
